### ISSUE TITLE
Критическая ошибка в CDEKDelivery

### ISSUE THREAD

**Issue by yslpn** [cdek-it/wordpress#12]
Здравствуйте. Перешёл на плагин из каталога wordpress https://wordpress.org/plugins/cdekdelivery/ и теперь получаю ошибку и не могу активировать плагин.

Люди тут тоже пишут, что не работает https://wordpress.org/support/topic/%d0%bf%d0%bb%d0%b0%d0%b3%d0%b8%d0%bd-%d0%bd%d0%b5-%d1%80%d0%b0%d0%b1%d0%be%d1%82%d0%b0%d0%b5%d1%82-30/

Версия WordPress 6.5.4
Текущая тема: Twenty Twenty-Three (версия 1.4)
Проблемный плагин: CDEKDelivery (версия 3.21.0)
Версия PHP 8.1.27

Подробности ошибки
===================================
Ошибка с типом E_ERROR возникла на строке 193 файла /home/u157372703/domains/fronda.press/public_html/wp-content/plugins/cdekdelivery/src/Loader.php. Сообщение об ошибке: Uncaught Error: Class "Cdek\Managers\TaskManager" not found in /home/u157372703/domains/fronda.press/public_html/wp-content/plugins/cdekdelivery/src/Loader.php:193
Stack trace:
#0 /home/u157372703/domains/fronda.press/public_html/wp-content/plugins/cdekdelivery/cdek.php(31): Cdek\Loader->__invoke()
#1 /home/u157372703/domains/fronda.press/public_html/wp-settings.php(517): include_once('/home/u15737270...')
#2 /home/u157372703/domains/fronda.press/public_html/wp-config.php(103): require_once('/home/u15737270...')
#3 /home/u157372703/domains/fronda.press/public_html/wp-load.php(50): require_once('/home/u15737270...')
#4 /home/u157372703/domains/fronda.press/public_html/wp-login.php(12): require('/home/u15737270...')
#5 {main}
  thrown

**Comment by vermorag** [comment]
Добрый день. Вчера в процессе выгрузки в стор вордпресса произошел сбой.
Только что перевыложил туда правильную версию.

Можете переустановить версию из стора, или поставить из релиза на гитхабе, должно работать.

**Comment by yslpn** [comment]
@vermorag спасибо, переустановка плагина в сторе помогла.
