### ISSUE TITLE
Ошибка выбора ПВЗ

### ISSUE THREAD

**Issue by olzah78** [cdek-it/wordpress#14]
Добрый день. В настройках при выборе ПВЗ отправки после ввода адреса происходит переключение на вкладку "Доставка от двери". Если адрес не вводить, а указывать на карте - тоже самое - переключается на Доставку от двери. 
Так и не удалось выбрать ПВЗ.
Видимо из-за этого доставка так и не появилась в checkout

**Comment by vermorag** [comment]
Добрый день. ПВЗ нужно выбирать прям с карты, кликом на его иконку.
При клике в свободном месте - карат переключает режим.

**Comment by olzah78** [comment]
![Снимок2](https://github.com/cdek-it/wordpress/assets/163751137/46d0645d-3fe2-405f-9d0d-158d94c1572a)

Список ПВЗ не появляется и на карте ПВЗ то же нет
