### ISSUE TITLE
Ошибки или недочеты плагина.

### ISSUE THREAD

**Issue by mraznoe** [cdek-it/wordpress#15]
Здравствуйте!
Спасибо за разработку плагина для Woocommerce. В ближайшее время планировали переходить на него. Но столкнулись с рядом сложностей.
Ниже список того, что не хватает или работает неверно.
 
1. Неверно считает доставку из Санкт-Петербурга в Петергоф, плагин насчитал 150 руб. В кабинете 210 руб. Если менять на Санкт-Петербург или Москва, считает верно, а Петергоф ставит цену Санкт-Петербурга.
 
CDEK: Доставка в постамат, (2-3 дней)
Код тарифа: 368
Вес: 390g
Длина: 10
Ширина: 27
Высота: 10
Выбранный ПВЗ: PET27 (ул. Парковая, 14А)
 
2. Если не все поля в корзине заполнены, выдает ошибку прямо с путями

Не выбран ПВЗ для доставки заказа.
Argument 1 passed to Cdek\Helper::validateCdekPhoneNumber() must be of the type string, null given, called in /var/www/wp8026/data/site.ru/wp-content/plugins/cdekdelivery/src/Validator/CheckoutProcessValidator.php on line 57
Фамилия для выставления счета является обязательным полем.
Имя Отчество для выставления счета является обязательным полем.
Телефон для выставления счета является обязательным полем.
Email для выставления счета является обязательным полем.
 
3. Не хватает в настройках плагина поле для указания веса упаковки. Обычно в плагинах такого типа делают добавку на упаковку, она тоже дает вес и значительно может увеличивать стоимость доставки.
 
4. Не хватает в настройках плагина поле для указания доп. стоимость к доставке. Например, магазин закладывает стоимость упаковки, забора груза и др. Плагин выдает стоимость доставки без учета этих затрат.
 
5. В письмо о новом заказе не добавляет адрес выбранного пункта выдачи. В Админке заказа есть, а в письме нет. 

6. Считает неверно габариты, если в заказе у одного товара указаны размеры, а у другого нет. Т.е. он не берет для товара у которого нет габаритов значения по 
умолчанию.

7. Не хватает алиасов для населенных пунктов. Например, Горелово. Если пользователь введет Горелово, то плагин не предложит доставку СДЭК, так как правильно для плагина ввести "территория Горелово". Покупатель вряд ли догадается. Соответственно покупатель не смог оформить заказ у нас на сайте.

**Comment by DEMAxx** [comment]
1. Взяли в работу, исправим ошибку определения местоположений для расчета доставки
2. Уточните версию плагина, ошибка была исправлена ранее

Спасибо за предложения по доработке! Мы обязательно будет добавлять новый функционал в будущих релизах!

**Comment by mraznoe** [comment]
2 Ошибка ушла после обновления. 

Но есть еще момент, плагин отключает доставку другой службы доставки, так как в автоподсказке выбора населенного пункта добавляется слово "город", например Санкт-Петербург город, Новоселово деревня и тп.

**Comment by mraznoe** [comment]
2 Ошибка ушла после обновления. 

Но есть еще момент, плагин отключает доставку другой службы доставки, так как в автоподсказке выбора населенного пункта добавляется слово "город", например Санкт-Петербург город, Новоселово деревня и тп.

**Comment by vermorag** [comment]
Добрый день. В нашем плагине нет функционала автокомплита, соответственно добавлять слово "город" он не может.

**Comment by vermorag** [comment]
5. Номер вашей задачи на доработку WP-34
6. Для того, чтобы габариты по умолчанию применялись к товару (а не к упаковке, в целом), надо поставить соответствующую отметку в настройках

**Comment by mraznoe** [comment]
6. Уточните где находится данная настройка.
7. Если нет подстановки города, покупатель введет "Горелово", то пункт выбора ПВЗ вообще не появится даже. Метод доставки СДЭК не отобразится.

**Comment by mraznoe** [comment]
8. Есть предложение на карте отображать все пункты выдачи. А не только в указанном населенном пункте. Иногда человек и не знает, что в пригороде, где он живет есть СДЭК. А так карту открыл СПб, а рядом показывает еще и Кудрово, а там новый пункт, например, и он близко к дому.
Или человек считает, что он живет в СПб, а по факту Новое Девяткино, а это разные населенные пункты для СДЭК.

**Comment by vermorag** [comment]
8. Такой запрос у нас был (WP-36), однако есть такой момент, что вордпресс показывает стоимость доставки ДО того как будет открыта наша карта. Он запрашивает расчет у плагина с теми параметрами, которые ввели в его поля.
И может получиться ситуация, когда человек увидел 100 рублей, а потом переставил в Мурино, а там уже 120р, например.

В инсейлз этот функционал реализован так, что ПВЗ показываются в регионе, а не в конкретном городе, но и там есть сложности с выбором и пользователи просили сократить только до города (мы сделали переключатель).

Поэтому еще думаем как лучше реализовать. Если есть идеи - буду рад услышать.

**Comment by vermorag** [comment]
7. Мы совместимы с автокомплитом от дадаты, сами же автокомплит для чекаута мы реализовывать не будем для исключения конфликтов с другими модулями/плагинами.

**Comment by mraznoe** [comment]
![неправильно](https://github.com/user-attachments/assets/ea482f2b-448f-4b5c-b306-48434549c90e)
Неверно приходит ПВЗ в письме, мы обрабатываем заказы из писем, а не админки. Получаются частые накладки.
![неверно](https://github.com/user-attachments/assets/4fb6f7b3-0908-4472-bf40-aac4569c9b17)

**Comment by mraznoe** [comment]
"Для того, чтобы габариты по умолчанию применялись к товару (а не к упаковке, в целом), надо поставить соответствующую отметку в настройках"
Уточните, пожалуйста, где поставить отметку?

**Comment by vermorag** [comment]
![изображение](https://github.com/user-attachments/assets/a8b47433-6463-4624-89bd-c32d63a4f77b)

**Comment by mraznoe** [comment]
Напишите подробнее как это работает. Пока непонятно как это решает проблему, если у одного из товаров в корзине не указан размер. А у всех остальных указан.

**Comment by denism300** [comment]
Приветствую! 
На тестовом хостинге плагин работал, все ок. После переноса сайта на боевой, при попытке зайти в настройки WooCommerce на вкладку "Доставка" ошибка 500, в логах wordpress (debug.log) следующее:

> [05-Aug-2024 12:52:07 UTC] PHP Fatal error:  Out of memory (allocated 612368384 bytes) (tried to allocate 12288 bytes) in /var/www/u2624099/data/www/xn--80aaa.shop/wp-includes/functions.php on line 650
[05-Aug-2024 12:52:07 UTC] PHP Fatal error:  Out of memory (allocated 612368384 bytes) (tried to allocate 20480 bytes) in /var/www/u2624099/data/www/xn--80aaa.shop/wp-includes/class-wp-error.php on line 230

Если плагин деактивировать, то все ок. 
При попытке удаления плагина в админке ошибка:

> Удаление не удалось: .wp-die-message { display: none; } Fatal error: Uncaught Error: Cdek\Helper::getActualShippingMethod(): Return value must be of type Cdek\CdekShippingMethod, null returnedin /var/www/u2624099/data/www/xn--80aaa.shop/wp-content/plugins/cdekdelivery/src/Helper.php on line 67Call stack:Cdek\Helper::getActualShippingMethod()wp-content/plugins/cdekdelivery/src/Helpers/DBTokenStorage.php:17Cdek\Helpers\DBTokenStorage::flushCache()wp-content/plugins/cdekdelivery/src/Actions/FlushTokenCacheAction.php:12Cdek\Actions\FlushTokenCacheAction::__invoke()wp-content/plugins/cdekdelivery/src/Uninstaller.php:15Cdek\Uninstaller::__invoke()wp-content/plugins/cdekdelivery/uninstall.php:13include_once()wp-admin/includes/plugin.php:1314uninstall_plugin()wp-admin/includes/plugin.php:970delete_plugins()wp-admin/includes/ajax-actions.php:4770wp_ajax_delete_plugin()wp-includes/class-wp-hook.php:324WP_Hook::apply_filters()wp-includes/class-wp-hook.php:348WP_Hook::do_action()wp-includes/plugin.php:517do_action()wp-admin/admin-ajax.php:192Query MonitorНа сайте возникла критическая ошибка.Узнайте больше про решение проблем с WordPress.

Если удалить папку плагина вручную и установить заново - вышеперечисленные проблемы не уходят.
Версия PHP 8.3.8. 
Понижение версии до 7.4.33 ничего не меняет, в том числе, после удаления и новой установки плагина.
Единственное, при попытке открыть настройки плагина ошибки пишутся уже в логи сервера, а не в debug.log

> [Mon Aug 05 16:23:36.566984 2024] [fcgid:warn] [pid 160776:tid 140112084064000] (104)Connection reset by peer: [client 31.134.187.21:50384] mod_fcgid: error reading data from FastCGI server, referer: https://xn--80aaa.shop/wp-admin/admin.php?page=wc-settings&tab=shipping
[Mon Aug 05 16:23:36.567043 2024] [core:error] [pid 160776:tid 140112084064000] [client 31.134.187.21:50384] End of script output before headers: admin.php, referer: https://xn--80aaa.shop/wp-admin/admin.php?page=wc-settings&tab=shipping

**Comment by vermorag** [comment]
>При попытке удаления плагина в админке ошибка
Ошибку забрал, в ближайшем релизе поправим

>На тестовом хостинге плагин работал, все ок. После переноса сайта на боевой, при попытке зайти в настройки WooCommerce на вкладку "Доставка" ошибка 500, в логах wordpress (debug.log) следующее
Можете подсказать - у вас стоит платежный плагин от Robokassa?

**Comment by denism300** [comment]
> Можете подсказать - у вас стоит платежный плагин от Robokassa?
Нет, используется шлюз от АльфаБанка

**Comment by vermorag** [comment]
>Нет, используется шлюз от АльфаБанка

>При попытке удаления плагина в админке ошибка

Проверьте, пожалуйста, с последней версией [3.22.1](https://github.com/cdek-it/wordpress/releases/tag/v3.22.1). Если ошибка не уйдет, то потребуется диагностика вашего магазин. Для этого потребуется отправить на [cms-integrator@cdek.ru](mailto:cms-integrator@cdek.ru) ссылку на вход в панель администрирования, а также логин и пароль. Во избежание путаницы, в письме также укажите ссылку на тикет в гитхаб, а в теме "Предоставление доступов". 

Обращу внимание, что данная почта используется только для безопасной передачи учетных данных, техническая поддержка по ней не производится.

После диагностики, отпишусь в комментариях к текущему тикету.

**Comment by vermorag** [comment]
> Напишите подробнее как это работает.

Подробнее о работе калькулятора габаритов в плагине можно прочитать в [FAQ](https://github.com/cdek-it/wordpress/wiki/FAQ)

**Comment by denism300** [comment]
> Проверьте, пожалуйста, с последней версией [3.22.1](https://github.com/cdek-it/wordpress/releases/tag/v3.22.1). Если ошибка не уйдет, то потребуется диагностика вашего магазина. Для этого потребуется отправить на [cms-integrator@cdek.ru](mailto:cms-integrator@cdek.ru) ссылку на вход в панель администрирования, а также логин и пароль. Во избежание путаницы, в письме также укажите ссылку на тикет в гитхаб, а в теме "Предоставление доступов".

После обновления плагин не вызывает ошибку при переходе в настройки. Спасибо за оперативность
