### ISSUE TITLE
Получить квитанцию

### ISSUE THREAD

**Issue by mercury4** [cdek-it/wordpress#19]
Не работает функциональность "Получить квитанцию". Пытается открыть квитанцию по url /wp-json/cdek/v1/get-waybill?number=ххх, где ххх - номер заказа, но возращает ошибку. 
Попытался разобратся в работе - вообще такой ендпойт не регистрируется. Помогите разобратся.

**Comment by DEMAxx** [comment]
Endpoint зарегистрирован в Loader - add_action('rest_api_init', new RestController)
Можете сказать какой сайт, заказ, версию плагина, WC и Wordpress и отправить ошибку?

**Comment by vermorag** [comment]
`/wp-json/cdek/v1/get-waybill?number=ххх` - это старый формат ссылки на накладную. Сейчас в коде он не использует (поэтому его и не находите, если смотрите на код с гитхаба).
Советую обновиться до последней версии и проверить ошибку там.
