### ISSUE TITLE
Не отображается выбранный ПВЗ

### ISSUE THREAD

**Issue by olgatrick** [cdek-it/wordpress#20]
Добрый день!

Как сделать так, чтобы в письме которое приходит на emal администратора с уведомлением о новом заказе: были добавлены данные о выбранном пвз?
Клиент при оформлении заказа может выбрать пвз по одному адресу, а в поля вбить свой личный домашний адрес. По итогу когда приходит заказ на почту: мы видим только личный адрес клиента и спосбо доставки "СДЭК ДО ПВЗ", а адреса этого выбранного ПВЗ мы не видим.
Как решить эту проблему?

**Comment by olgatrick** [comment]
Или можно ли сделать так, как в других плагинах по доставке: если клиент выбирает какой-то пвз, то данные в поля для заполгнения "адрес" подтягиваются автоматически в зависимости от адреса пвз??

**Comment by vermorag** [comment]
Добрый день.
>Как сделать так, чтобы в письме которое приходит на emal администратора с уведомлением о новом заказе: были добавлены данные о выбранном пвз?

В настоящий момент - никак. У нас уже есть запрос на доработку с данной функциональностью под номером WP-34.
Статус задач, взятых на доработку, вы можете отслеживать в нашей рассылке обновлений. Для подключения к рассылке, напишите в наш чат технической поддержки https://t.me/cdek_it_bot раздел Интеграция для интернет-магазинов.

>Или можно ли сделать так, как в других плагинах по доставке: если клиент выбирает какой-то пвз, то данные в поля для заполгнения "адрес" подтягиваются автоматически в зависимости от адреса пвз??

В старых версиях плагина так и работало, однако были массовые запросы по отключению данной функциональности, соответственно сейчас только планиируется добавить код ПВЗ в шаблон рассылки от вордпресса.

Обращу внимание, что клиенту итак приходит сообщение от компании СДЭК о регистрации заказа со ссылкой, где можно его отследить и посмотреть ПВЗ выдачи.
