### ISSUE TITLE
Если не заполнен номер телефона

### ISSUE THREAD

**Issue by mraznoe** [cdek-it/wordpress#22]
Версия 3.21.6 
Если не заполнен номер телефона выдает клиенту ошибку с путями
Argument 1 passed to Cdek\Helper::validateCdekPhoneNumber() must be of the type string, null given, called in /var/www//data/site.ru/wp-content/plugins/cdekdelivery/src/Validator/CheckoutProcessValidator.php on line 57

**Comment by mraznoe** [comment]
И ещё:
1. Хотелось бы добавлять к стоимости доставки фиксированную сумму, а не проценты. Обычно затраты не особо зависят от стоимости доставки, они обычно фиксированные (забор груза, стоимость тары и тп.)
2. Можно убрать сроки доставки - добавить галочку не показывать сроки?

**Comment by vermorag** [comment]
Добрый день.

> Если не заполнен номер телефона выдает клиенту ошибку с путями

В 3.22.1 должна уйти 

> Хотелось бы добавлять к стоимости доставки фиксированную сумму, а не проценты. Обычно затраты не особо зависят от стоимости доставки, они обычно фиксированные (забор груза, стоимость тары и тп.)

Это делается в настройках плагина.
![image](https://github.com/user-attachments/assets/67d3bd16-4790-40c5-b1aa-7333b7a7a07a)

> Можно убрать сроки доставки - добавить галочку не показывать сроки?

Сейчас такого функцинала нет, вы можете вынести его в пожелания в [соответствующий раздел](https://github.com/cdek-it/wordpress/discussions/new?category=ideas).
