### ISSUE TITLE
Сохранение квитанции или ШК

### ISSUE THREAD

**Issue by frozzen-git** [cdek-it/wordpress#23]
После получения накладной или ШК, открытой в новом окне с url = blob:https://мой.домен/79c46a20-39bc-484a-957c-8a7ce0820507 есть возможность только распечатать полученный документ. Попытка сохранить локально приводит к ошибке "Проверьте подключение к интернету" либо "Загрузка прервана" (Chrome и Яндекс).
Как сохранить такой документ для внутреннего использования?

**Comment by vermorag** [comment]
Добрый день. Если не работает скачивание, вы можете попробовать распечатать документ с помощью встроенного принтера "Microsoft Print ot PDF", он тоже сохраняет документ как PDF.

**Comment by frozzen-git** [comment]
> Добрый день. Если не работает скачивание, вы можете попробовать распечатать документ с помощью встроенного принтера "Microsoft Print ot PDF", он тоже сохраняет документ как PDF.

Добрый день! Ну я то, пожалуй, смогу найти выход, хотя и не видел Microsoft'а лет 15 )). 
А вот тетушки из отдела продаж будут в замешательстве каждый раз. А если еще и с iPhone надо будет его кому-то переправить....
На мой взгляд, проблема важная и требует продуманного решения.
Спасибо

**Comment by vermorag** [comment]
Проблема только "яблочная"?

У меня есть пара идей как можно переиграть этот момент, но на винде не могу поймать.

**Comment by frozzen-git** [comment]
> Проблема только "яблочная"?
> 
> У меня есть пара идей как можно переиграть этот момент, но на винде не могу поймать.

Здравствуйте! Почему "яблочная"?! 
Сохранение в обычном, привычном для любого пользователя любого браузера, виде не работает. В любом браузере в окне просмотра ПДФа есть кнопка "Сохранить". Она и не работает.
Можно конечно выходить из положения так, как Вы предложили выше, но способ этот для юзера даже среднего уровня не очевиден.

**Comment by frozzen-git** [comment]
> Добрый день. Проверьте с последней версией.

Проверил в Хроме, всё работает. Думаю и на других браузерах/платформах проблем не будет. Спасибо
