### ISSUE TITLE
Неверно приходят данные о выбранном ПВЗ в письме

### ISSUE THREAD

**Issue by mraznoe** [cdek-it/wordpress#25]
Здравствуйте! Неверно приходят данные о выбранном ПВЗ в письме
Мы обрабатываем заказы из писем, часто случаются накладки поэтому.
![неправильно](https://github.com/user-attachments/assets/4a2a8257-3918-4343-ba2a-d3b432af60b8)
![неверно](https://github.com/user-attachments/assets/2b13b67a-0b06-4c11-96af-18966a071719)

**Comment by vermorag** [comment]
Добрый день. В настоящий момент в плагине нет функционала сообщать адрес ПВЗ в письме.
