### ISSUE TITLE
Не инициализируется плагин в checkout форме

### ISSUE THREAD

**Issue by ceobit** [cdek-it/wordpress#27]
Версия плагина: 3.22.1
Используются автокомплит от Dadata

Получаю ошибку 
```
Warning: Undefined array key "city" in /var/www/my-line.app/wp-content/plugins/cdekdelivery/src/Actions/CalculateDeliveryAction.php on line 50

Warning: Undefined array key "city" in /var/www/my-line.app/wp-content/plugins/cdekdelivery/src/Actions/CalculateDeliveryAction.php on line 51
```

В коде нахожу эти строки
<img width="816" alt="image" src="https://github.com/user-attachments/assets/c029a208-72b0-4c6f-a3dd-183806f47345">

Форму заполняю полностью, Вроде все настройки установил. Что-то пропустил?

**Comment by vermorag** [comment]
Добрый день. Это не ошибка, а предупреждение. Если у вас в настройках плагина не заполнен один из вариантов доставки (от пвз или от двери), то данное предупреждение будет появляться. На функциональность плагина оно не влияет.
