### ISSUE TITLE
Грамматические ошибки в админке

### ISSUE THREAD

**Issue by denism300** [cdek-it/wordpress#28]
Просьба исправить грамматические ошибки. Это не критично, но для глаз неприятно.
![image](https://github.com/user-attachments/assets/bfcb527f-2e20-4edb-8699-8bf0f2b83c67)
![image](https://github.com/user-attachments/assets/2652fc6f-0fb3-4151-b387-891e9d3387ec)
![image](https://github.com/user-attachments/assets/f63f484f-b219-40ef-8bd0-a29996ae5d7c)

**Comment by vermorag** [comment]
Добрый день. Вносить предложения по перводу плагина вы можете самостоятельно напрямую на [странице плагина](https://translate.wordpress.org/projects/wp-plugins/cdekdelivery/).
