### ISSUE TITLE
Услуги доставки в большом количестве

### ISSUE THREAD

**Issue by d-nikolaev** [cdek-it/wordpress#35]
Плагин генерирует разные виды услуг с приставкой в скобках количество дней.
![photo_2024-09-06_13-53-32](https://github.com/user-attachments/assets/6e022448-24fe-4a36-90f4-6b1c2206bb50)
Возможно ли оставить только виды доставок без дней?

**Comment by vermorag** [comment]
Добрый день. Это репозиторий интеграции с плагином Woocommerce. У вас на скриншоте - 1С. Вам необходимо обратиться к разработчику вашего модуля интеграции.

**Comment by d-nikolaev** [comment]
Скриншот из 1С был чисто для примера объёма нагенерированных услуг. У нас 1С получает данные о заказах из интернет магазина. Что в магазине создалось то в 1С и загрузилось.
Приписку в днях в виду доставки делает плагин.
Вот другой скриншот из корзины.
![корзина](https://github.com/user-attachments/assets/849494bd-ce42-455c-9223-f61163d6b5f0)
А вот настройки плагина.
![настройки](https://github.com/user-attachments/assets/3fc980d8-d2c1-4af1-9259-189ad9dd1bec)

**Comment by vermorag** [comment]
Одинаковые названия услуг выводятся, поскольку заданы свои индивидуальные наименования тарифов (судя по всему, для разных услуг одинаковые).
Приписка в днях доставки к названию не является ошибкой - это ожидаемое поведение плагина.
