### ISSUE TITLE
Ошибка [CDEKDelivery] Server error

### ISSUE THREAD

**Issue by yslpn** [cdek-it/wordpress#49]
Привет. Получаю ошибку при попытке отправить заказ в СДЕК через админку.

СДЕК 3.23.3
WooCommerce 9.3.3
Wordpress 6.6.2

Request URL:
https://fronda.press/wp-json/official_cdek/order/918/create?_wpnonce=80d8e8a836&_locale=user

Запрос: 

`{"packages":[{"length":"27","width":"20","height":"1"}]}`

Ответ:

```
{
    "code": "cdek_error",
    "message": "Error happened at CDEKDelivery",
    "data": {
        "status": 500
    },
    "additional_errors": [
        {
            "code": "api.server",
            "message": "[CDEKDelivery] Server error",
            "data": {
                "code": "page_not_found",
                "message": "The requested page does not exist."
            }
        }
    ]
}
```

<img width="302" alt="image" src="https://github.com/user-attachments/assets/f41174f1-31af-4260-93e3-d11ae1b62de2">

<img width="597" alt="image" src="https://github.com/user-attachments/assets/ab41ba83-1f70-40b9-a02a-09b36a429977">

**Comment by vermorag** [comment]
Добрый день, спасибо за полную отладочную информацию. Ваша версия плагина была отозвана из маркета и сейчас последняя актуальная - [3.22.3](https://github.com/cdek-it/wordpress/releases/tag/v3.22.3).
Попробуйте скачать ее архив из [маркета](https://wordpress.org/plugins/cdekdelivery/) или со [страницы релиза](https://github.com/cdek-it/wordpress/releases/tag/v3.22.3) и установить в панели администратора из архива.

В текущем обновлении были изменения, который должны были упростить функционал для пользователя при создании заказа: добавили все доступные печатные формы для ШК и переделали автоматизацию создания заказа, чтобы быть совместимыми с любыми платежными системами и автоматически создавать заказ даже если что-то пошло не так и вам пришлось вручную поменять статус заказа на "оплачен". Поэтому торопились, хотели уменьшить срок выпуска релиза, чтобы вы скорее могли им воспользоваться, однако не учли все ситуации и потеряли работоспособность функционала. Поправим нашу тестовую среду, добавим больше тестирования во избежание критических ошибок в дальнейшем. Приносим извинения за причиненные неудобства и заранее благодарим за понимание.
