### ISSUE TITLE
Из-за плагина не получается добавить товар в корзину

### ISSUE THREAD

**Issue by Guihal** [cdek-it/wordpress#5]
[26-May-2024 12:06:22 UTC] PHP Fatal error:  Uncaught TypeError: Typed property Cdek\Exceptions\CdekException::$data must be array, null used in /home/lissanasho/public_html/wp-content/plugins/cdek/src/Exceptions/CdekException.php:24
Stack trace:
```
#0 /home/lissanasho/public_html/wp-content/plugins/cdek/src/CdekApi.php(74): Cdek\Exceptions\CdekException->__construct('[CDEKDelivery] ...', 'cdek_error.toke...', NULL, true)
#1 /home/lissanasho/public_html/wp-content/plugins/cdek/src/Helpers/DBTokenStorage.php(83): Cdek\CdekApi->fetchToken()
#2 /home/lissanasho/public_html/wp-content/plugins/cdek/src/Helpers/DBTokenStorage.php(69): Cdek\Helpers\DBTokenStorage->fetchTokenFromApi()
#3 /home/lissanasho/public_html/wp-content/plugins/cdek/src/Helpers/DBTokenStorage.php(29): Cdek\Helpers\DBTokenStorage->updateToken()
#4 /home/lissanasho/public_html/wp-content/plugins/cdek/src/CdekApi.php(61): Cdek\Helpers\DBTokenStorage->getToken()
#5 /home/lissanasho/public_html/wp-content/plugins/cdek/src/Helpers/DeliveryCalc.php(33): Cdek\CdekApi->checkAuth()
#6 /home/lissanash in /home/lissanasho/public_html/wp-content/plugins/cdek/src/Exceptions/CdekException.php on line 24
```

**Comment by KPABOOKING** [comment]
Добрый день, такая же ситуация.
private ?array $data;
$this->data = $data ?? [];

Не исправило ситуацию, отваливается токен СДЭК.

**Comment by vermorag** [comment]
Добрый день. Вы можете попробовать установить [эту](https://github.com/cdek-it/wordpress/files/15450243/cdek.zip) версию плагина. В ней добавил обработку ошибки.

**Comment by inclo** [comment]
> Добрый день. Вы можете попробовать установить [эту](https://github.com/cdek-it/wordpress/files/15450243/cdek.zip) версию плагина. В ней добавил обработку ошибки.

Обработка это хорошо, но способ доставки CDEK не работает.
В чем проблема, есть ли решение?
Если проблема на стороне серверов CDEK, когда решится?

**Comment by vermorag** [comment]
У нас произошел массовый сбой. 

Сейчас на сервисах ведутся технические работы, к сожалению, почти все системы недоступны. 

Сроки восстановления, к сожалению, мы предоставить не можем. На устранение проблем направлен весь доступный ресурс инженеров.

**Comment by vermorag** [comment]
Выпущена [3.20.1](https://github.com/cdek-it/wordpress/releases/tag/v3.20.1)
