### ISSUE TITLE
Мини-корзина перестает работать при активации плагина

### ISSUE THREAD

**Issue by glSPICE** [cdek-it/wordpress#50]
Здравствуйте. Мини-корзина AJAX перестает работать с активированным плагином на страницах без авторизации пользователя. При добавлении товара со страницы каталога в консоли ошибка

GET https://jj-sila-shop.ru/wp-json/wc/store/v1/cart?_locale=user 500 (Internal Server Error)

А после обновления страницы более подробно (см скрин)
![2024-10-21 11 25 44](https://github.com/user-attachments/assets/24c56694-7817-4cb3-b9b9-54c3ceeab62d)

Когда я авторизован под админом все работает. У обычных пользователей не проверял. При отключении плагина работает исправно.

**Comment by glSPICE** [comment]
Проверял на стандартной теме, поведение тоже самое

**Comment by vermorag** [comment]
Добый день. Подскажите - какая версия плагина установлена?

**Comment by glSPICE** [comment]
> Добый день. Подскажите - какая версия плагина установлена?

Версия 3.23.3, последняя релизная.

**Comment by glSPICE** [comment]
Именно она и установлена, но почему-то версия в перечне плагинов в описании указана 3.23.3, а при нажатии "подробнее" уже 3.22.3. Плагин установлен буквально три дня назад. Сразу не заметил проблему, потому что все хорошо когда ты вошел в аккаунт вордпресса. Проблема только у тех, кто собирается покупать в первый раз или у кого успели куки слететь.

**Comment by vermorag** [comment]
Если в перечне плагинов указана 3.23, значит она и стоит. Скачайте версию 3.22 и установите из архива.

**Comment by glSPICE** [comment]
Действительно, установил плагин из архива и все заработало. Спасибо!

**Comment by vermorag** [comment]
Версия плагина 3.23.3 была отозвана из маркета и сейчас недоступна, однако автоматическое обновление на версию "ниже" - 3.22 не предусмотрено системой.
