### ISSUE TITLE
[CDEKDelivery] Failed to get the token

### ISSUE THREAD

**Issue by glSPICE** [cdek-it/wordpress#58]
Здравствуйте. При открытии в админке любого заказа с доставкой сдэк получаю фатал эррор (ниже).

Версия плагина 3.22.4
Версия ВП 6.7
Версия ВК 9.4.1
Везде последние версии в общем.

Ошибку нашли сейчас, но возможно она появилась после последнего обновления ВП. Ключи все указаны и раньше были указаны те же, когда все работало

Также при оформлении заказа не выводятся методы доставки СДЭК и не обновляется AJAX корзина при добавлении товара на сайте (тоже самое было в прошлый раз со старой версией плагина. Можно как-то сделать, чтобы добавление товара в корзину никак не касалось плагина до момента оформления? из-за проблем со СДЭКом страдают покупатели с другими способами доставки, а их большинство)

[Mon Nov 18 15:55:38.836782 2024] [php:error] [pid 61283:tid 61283] [client 93.80.124.76:0] PHP Fatal error:  Uncaught Cdek\\Exceptions\\CdekApiException: [CDEKDelivery] Failed to get the token in /home/jj-3405999/my-wc-shop.ru/docs/wp-content/plugins/cdekdelivery/src/CdekApi.php:80\nStack trace:\n#0 /home/jj-3405999/my-wc-shop.ru/docs/wp-content/plugins/cdekdelivery/src/Helpers/DBTokenStorage.php(90): Cdek\\CdekApi->fetchToken()\n#1 /home/jj-3405999/my-wc-shop.ru/docs/wp-content/plugins/cdekdelivery/src/Helpers/DBTokenStorage.php(76): Cdek\\Helpers\\DBTokenStorage->fetchTokenFromApi()\n#2 /home/jj-3405999/my-wc-shop.ru/docs/wp-content/plugins/cdekdelivery/src/Helpers/DBTokenStorage.php(33): Cdek\\Helpers\\DBTokenStorage->updateToken()\n#3 /home/jj-3405999/my-wc-shop.ru/docs/wp-content/plugins/cdekdelivery/src/CdekApi.php(69): Cdek\\Helpers\\DBTokenStorage->getToken()\n#4 /home/jj-3405999/my-wc-shop.ru/docs/wp-content/plugins/cdekdelivery/src/UI/MetaBoxes.php(47): Cdek\\CdekApi->checkAuth()\n#5 /home/jj-3405999/my-wc-shop.ru/docs/wp-includes/class-wp-hook.php(324): Cdek\\UI\\MetaBoxes::registerMetaBoxes('shop_order', Object(WP_Post))\n#6 /home/jj-3405999/my-wc-shop.ru/docs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#7 /home/jj-3405999/my-wc-shop.ru/docs/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /home/jj-3405999/my-wc-shop.ru/docs/wp-admin/includes/meta-boxes.php(1716): do_action('add_meta_boxes', 'shop_order', Object(WP_Post))\n#9 /home/jj-3405999/my-wc-shop.ru/docs/wp-admin/edit-form-advanced.php(271): register_and_do_post_meta_boxes(Object(WP_Post))\n#10 /home/jj-3405999/my-wc-shop.ru/docs/wp-admin/post.php(206): require('/home/jj-340554...')\n#11 {main}\n  thrown in /home/jj-3405999/my-wc-shop.ru/docs/wp-content/plugins/cdekdelivery/src/CdekApi.php on line 80, referer: https://my-wc-shop.ru/wp-admin/edit.php?s=16162&post_status=all&post_type=shop_order&action=-1&m=0&_customer_user&shipping_method_filter&user_billing_address&woaf_filter_start_date&woaf_filter_end_date&order_total_start&order_total_end&paged=1&ddwc_meta_noncename=33063b51bd&16422=1858&16421=1858&16420=1858&16419=1858&16415=1858&16414=1858&16412=1859&action2=-1

**Comment by vermorag** [comment]
Добрый день.
В работе сервисов СДЭК наблюдался сбой, в следствии которого был недоступен API интеграции СДЭК.
На текущий момент проблема устранена.
Приносим извинения за неудобства.

>Можно как-то сделать, чтобы добавление товара в корзину никак не касалось плагина до момента оформления

Это сделать возможности нет, поскольку это функционал вызывается самим вукоммерсом, а на него наш плагин не влияет.
Однако мы переработали систему исключительных ситуаций в грядущем выпуске, это должно будет решить этот момент.

**Comment by glSPICE** [comment]
Благодарю! Действительно, в этот же день написали из СДЭКа, сказали про сбой.
По второму вопросу очень жду обновления, чтобы проблемы на стороне СДЭКа не затрагивали посетителей, которые даже не планировали заказывать доставку.
