### ISSUE TITLE
Ошибка при использовании блока woocomerce checkout block

### ISSUE THREAD

**Issue by veks** [cdek-it/wordpress#68]
Deprecated: Функция WC_Customer::get_postcode с версии 3.0 считается устаревшей! Используйте WC_Customer::get_billing_postcode. in wp-includes/functions.php on line 6114

Warning: Undefined array key 0 in wp-content/plugins/cdekdelivery/src/CdekApi.php on line 296

Warning: Trying to access array offset on null in wp-content/plugins/cdekdelivery/src/CdekApi.php on line 296

Warning: Undefined variable $data in wp-content/plugins/woocommerce/src/StoreApi/Schemas/ExtendSchema.php on line 239

**Comment by veks** [comment]
Проблема возникает если не введено (Населённый пункт, Область / район, Почтовый индекс)

**Comment by veks** [comment]
Проблема решена установка плагина версии 3.22.4

**Comment by veks** [comment]
Заголовок: ⚠️ Deprecated: WC_Customer::get_city и WC_Customer::get_postcode вызывают предупреждения при оформлении заказа незарегистрированным пользователем

Описание проблемы: Во время оформления заказа WooCommerce, если пользователь не авторизован и не заполнил поля billing_city и billing_postcode, возникает ошибка Deprecated. Эти функции устарели с версии 3.0 WooCommerce, но все еще используются. Рекомендуется заменить их на WC_Customer::get_billing_city() и WC_Customer::get_billing_postcode().

**Comment by veks** [comment]
Локация проблемы:
Класс: CheckoutHelper
Строка: 68

**Comment by vermorag** [comment]
Добрый день. Для отключения отображения сообщения достаточно отключить режим отладки в php.

Данный функционал используется для совместимости со сторонними темами и страницами оформления заказа, которые продолжают использовать устаревший функционал.
