### ISSUE TITLE
Ошибки несоответствия типов передаваемых параметров

### ISSUE THREAD

**Issue by golovanovya** [cdek-it/wordpress#78]
Плагин версии 4.0, PHP 7.4, Wordpress 6.0.9
Если не задан почтовый индекс, то возникает ошибка на странице checkout
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Cdek\CdekApi::cityCodeGet() must be of the type string, null given, called in cdekdelivery/src/UI/CheckoutMap.php on line 34 and defined in cdekdelivery/src/CdekApi.php:214
Ошибка генерации накладной и штрихкода
PHP Fatal error:  Uncaught TypeError: ini_set() expects parameter 2 to be string, int given in cdekdelivery/src/Actions/GenerateWaybillAction.php:32
PHP Fatal error:  Uncaught TypeError: ini_set() expects parameter 2 to be string, int given in cdekdelivery/src/Actions/GenerateBarcodeAction.php:35

**Comment by vermorag** [comment]
Добрый день. Ошибка была исправлена в версии [4.0.2](https://github.com/cdek-it/wordpress/releases/tag/v4.0.2)
