### ISSUE TITLE
Не отправляется заказ в СДЭК с товаром типа variable

### ISSUE THREAD

**Issue by golovanovya** [cdek-it/wordpress#79]
Плагин версии 4.0.2, PHP 7.4, Wordpress 6.0.9, Woocommerce 7.4.1
При нажатии на кнопку Отправить в СДЭК заказ с товаром типа variable возвращает ошибку
Сервер вернул ошибку валидации: [packages[0].items] is empty
![image](https://github.com/user-attachments/assets/b00aac23-d96b-46fb-9b1f-ceef674e52ec)

**Comment by vermorag** [comment]
Добрый день. В настоящий момент плагин поддерживает только товары с типами `simple` и `variation`, которые встроены в woocommerce.

**Comment by golovanovya** [comment]
Спасибо за помощь!

**Comment by golovanovya** [comment]
@vermorag Тип товара стандартный из Woocommerce. Похоже что у этого товара сменили тип c simple на variable после создания заказа

**Comment by vermorag** [comment]
Видимо, в этом и проблема. По умолчанию, при заказе вариативного товара в заказа попадает не он сам, а именно `variation`.
Кейс понял, воспроизведу и протестирую возможность работы с такими товарами.
Спасибо за объяснение.
